apiVersion: v1
kind: Namespace
metadata:
  name: fmc
  labels:
    name: fmc

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fmc-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fmc
  name: fmc-data
  labels:
    app: fmc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fmc-storage
  resources:
    requests:
      storage: 50Gi

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: fmc
  name: fmc-vnet
  labels:
    app: fmc-vnet
spec:
  selector:
    matchLabels:
      app: fmc-vnet
  template:
    metadata:
      labels:
        app: fmc-vnet
    spec:
      hostNetwork: true
      containers:
        - name: fmc-vnet
          image: saichler/fmc-vnet:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 34999
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          persistentVolumeClaim:
            claimName: fmc-data

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: fmc
  name: fmc-log-vnet
  labels:
    app: fmc-log-vnet
spec:
  selector:
    matchLabels:
      app: fmc-log-vnet
  template:
    metadata:
      labels:
        app: fmc-log-vnet
    spec:
      hostNetwork: true
      containers:
        - name: fmc-log-vnet
          image: saichler/fmc-log-vnet:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          persistentVolumeClaim:
            claimName: fmc-data

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: fmc
  name: fmc
  labels:
    app: fmc
spec:
  selector:
    matchLabels:
      app: fmc
  template:
    metadata:
      labels:
        app: fmc
    spec:
      containers:
        - name: fmc
          image: saichler/fmc:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          persistentVolumeClaim:
            claimName: fmc-data

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: fmc
  name: fmc-web
  labels:
    app: fmc-web
spec:
  selector:
    matchLabels:
      app: fmc-web
  template:
    metadata:
      labels:
        app: fmc-web
    spec:
      hostNetwork: true
      containers:
        - name: fmc-web
          image: saichler/fmc-web:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          persistentVolumeClaim:
            claimName: fmc-data

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: fmc
  name: fmc-member-web
  labels:
    app: fmc-member-web
spec:
  selector:
    matchLabels:
      app: fmc-member-web
  template:
    metadata:
      labels:
        app: fmc-member-web
    spec:
      hostNetwork: true
      containers:
        - name: fmc-member-web
          image: saichler/fmc-member-web:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          persistentVolumeClaim:
            claimName: fmc-data
